<?php
// includes/config.php
session_start();

// EDIT THESE to match your environment
$DB_HOST = 'localhost';
$DB_NAME = 'tea_shop';
$DB_USER = 'root';
$DB_PASS = '';

$options = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
];

try {
    $pdo = new PDO("mysql:host=$DB_HOST;dbname=$DB_NAME;charset=utf8mb4", $DB_USER, $DB_PASS, $options);
} catch (PDOException $e) {
    die("Database connection failed: " . $e->getMessage());
}

function e($str) {
    return htmlspecialchars($str, ENT_QUOTES, 'UTF-8');
}

// Gmail API (OAuth2) Mail Configuration — replaces SMTP
// See: public/gmail-oauth-setup.php for step-by-step setup
define('GMAIL_USER', 'admincapj@gmail.com');      // the sending Gmail address
define('GMAIL_CLIENT_ID', '');                    // from Google Cloud Console → Credentials → OAuth Client
define('GMAIL_CLIENT_SECRET', '');                // from Google Cloud Console → Credentials → OAuth Client
define('GMAIL_REFRESH_TOKEN', '');                // generated by public/gmail-oauth-setup.php
define('ADMIN_EMAIL', 'admincapj@gmail.com');
define('ADMIN_NAME', 'Captain J Admin');

define('APP_NAME', 'Captain J POS System');

// Auto-detect base URL
$basePath = '';
if (isset($_SERVER['SCRIPT_NAME'])) {
    $scriptName = $_SERVER['SCRIPT_NAME'];
    // Detect path up to /public/ (XAMPP/local) or compute from script dir (Hostinger)
    if (preg_match('#^(.+?/public)(/|$)#', $scriptName, $m)) {
        $basePath = $m[1];
    } else {
        $basePath = rtrim(dirname(dirname($scriptName)), '/');
    }
}
$basePath = ($basePath === '.' || $basePath === '') ? '' : $basePath;
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'] ?? 'localhost';
define('APP_BASE_URL', $protocol . '://' . $host . $basePath);
define('BASE_PATH', $basePath);

// Public-facing URL for email links (auto-detected from current request by default)
// Override for production: uncomment and set your domain
// define('APP_PUBLIC_URL', 'https://yourdomain.com');
if (!defined('APP_PUBLIC_URL')) {
    define('APP_PUBLIC_URL', APP_BASE_URL);
}

define('LOW_STOCK_THRESHOLD', 5);

// GCash Configuration — EDIT THESE
define('GCASH_NUMBER', '09536774000');
// GCash QR code image — replace this file with a QR code generated from your GCash app:
// 1. Open GCash app → tap "Receive Money" or "Scan to Pay"
// 2. Generate your store QR code
// 3. Take a screenshot and save it here
define('GCASH_QR_IMAGE', 'uploads/gcash-qr.jpg');

// PayMongo Configuration — EDIT THESE (get keys at https://dashboard.paymongo.com/)
define('PAYMONGO_SECRET_KEY_TEST', '');  // ← your test secret key
define('PAYMONGO_SECRET_KEY_LIVE', '');   // ← your live secret key
define('PAYMONGO_USE_TEST', true);                    // true = test mode, false = live
define('PAYMONGO_WEBHOOK_SECRET', '');       // ← set this in PayMongo dashboard webhooks
